version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-carsalon
    restart: always
    environment:
      - MYSQL_DATABASE=carsalon
      - MYSQL_ROOT_PASSWORD=carsalon_pass
    volumes:
      - mysql_data:/var/lib/mysql/

  api:
    build: .
    image: itsoda14/carsalon:latest
    command:
      - sh
      - -c
      - |
        dockerize -wait tcp://mysql:3306 -timeout 300s &&
        poetry run python manage.py collectstatic --noinput &&
        poetry run python manage.py migrate &&
        poetry run daphne -b 0.0.0.0 -p 8000 carsalon.asgi:application
    env_file:
      - docker-compose.env
    environment:
      - DOCKER_CONTAINER=True
      - VIRTUAL_HOST=onlydev.fun
      - LETSENCRYPT_HOST=onlydev.fun
    ports:
      - "8000:8000" 
    depends_on:
      - mysql
    volumes:
      - .:/itsoda
      - static_volume:/itsoda/static
    container_name: django-api

  nginx:
    build: 
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx_carsalon
    image: nginx_carsalon
    volumes:
      - static_volume:/itsoda/static
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
    environment:
      - NGINX_MAX_BODY_SIZE=200M
      - NGINX_CLIENT_MAX_BODY_SIZE=200M
    ports:
      - "80:80"
      - "443:443"
  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: carsalon_acme_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh

volumes:
  mysql_data: null
  static_volume:
  certs:
  vhost:
  html:
  acme: