# Generated by Django 4.2 on 2024-03-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="all_images")),
            ],
            options={
                "verbose_name": "Фотографию",
                "verbose_name_plural": "Фотографии",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.SmallIntegerField()),
                ("price", models.IntegerField()),
                ("owners", models.IntegerField()),
                ("engine", models.CharField(max_length=100)),
                ("power", models.IntegerField()),
                ("gearbox", models.CharField(max_length=100)),
                ("drive", models.CharField(max_length=100)),
                ("body_type", models.CharField(max_length=100)),
                ("mileage", models.IntegerField()),
                ("generation", models.CharField(max_length=100)),
                ("complete_set", models.CharField(max_length=100)),
                ("win_number", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("passed", "Passed")],
                        default="active",
                        max_length=100,
                    ),
                ),
                ("photos", models.ManyToManyField(to="cars.image")),
            ],
            options={
                "verbose_name": "автомобиль",
                "verbose_name_plural": "Автомобили",
            },
        ),
    ]
