# Generated by Django 4.2 on 2024-03-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="category",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
